workflows:
  android-shorebird-release:
    name: Android Shorebird Release
    max_build_duration: 60
    environment:
      flutter: stable
      # BAGIAN INI SANGAT PENTING:
      # Harus sama persis dengan nama grup di screenshot kamu (huruf kecil)
      groups:
        - shorebird
        - firebase
    scripts:
      - name: Install Shorebird & Build Release
        script: |
          set -e # Hentikan script jika ada error
          
          # 1. Install Shorebird
          echo "📥 Sedang menginstall Shorebird..."
          curl --proto '=https' --tlsv1.2 -sSf https://shorebird.dev/install.sh | bash
          
          # 2. Tambahkan Shorebird ke PATH (Hanya berlaku di sesi script ini)
          export PATH="$HOME/.shorebird/bin:$PATH"
          
          # 3. Verifikasi Instalasi
          echo "✅ Shorebird terinstall:"
          shorebird --version
          
          # 4. Setup Flutter Dependencies
          echo "📦 Mengambil dependencies..."
          flutter pub get
          
          # 5. Jalankan Shorebird Release
          # Perintah ini akan membuild .aab dan mendaftarkannya ke console Shorebird
          echo "🚀 Memulai Shorebird Release..."
          shorebird release android --flutter-version=stable
          
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      
    publishing:
      firebase:
        # Menggunakan token dari grup "firebase"
        firebase_token: $FIREBASE_TOKEN 
        android:
          # Menggunakan App ID dari grup "firebase"
          app_id: $FIREBASE_APP_ID 
          # Pastikan kamu sudah membuat grup tester bernama "testers" di Firebase Console
          # Atau ganti dengan nama grup yang sesuai, misal: "android-team"
          groups:
            - testers