workflows:
  android-shorebird-release:
    name: Android Shorebird Release & Firebase Dist
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - SHOREBIRD_TOKENS
    scripts:
      - name: Install Shorebird & Build Android Release
        script: |
          # 1. Install Shorebird
          curl --proto '=https' --tlsv1.2 -sSf https://shorebird.dev/install.sh | bash
          
          # 2. Tambahkan ke PATH sementara
          export PATH="$HOME/.shorebird/bin:$PATH"
          
          # 3. Verifikasi & Fetch dependencies
          flutter pub get
          
          # 4. Build Release (Menghasilkan .aab)
          shorebird release android
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $FIREBASE_APP_ID
          groups:
            - testers # Nama grup tester di Firebase kamu