workflows:
  android-shorebird-release:
    name: Android Shorebird Release
    max_build_duration: 60
    environment:
      flutter: stable
      # BAGIAN INI SANGAT PENTING:
      # Harus sama persis dengan nama grup di screenshot kamu (huruf kecil)
      groups:
        - shorebird
        - firebase
    scripts:
      - name: Install Shorebird, Build & Convert to APK
        script: |
          set -e
          
          # 1. Install Shorebird (Raw Source)
          echo "📥 Install Shorebird..."
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          
          # Tambahkan ke PATH
          export PATH="$HOME/.shorebird/bin:$PATH"
          
          # 2. Download bundletool (Alat pengubah AAB ke APK)
          echo "📥 Install Bundletool..."
          wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar -O bundletool.jar
          
          # 3. Build Release (KOREKSI: Tanpa flag --flutter-version)
          # Shorebird akan otomatis mendeteksi versi Flutter yang aktif di Codemagic
          echo "🚀 Shorebird Release..."
          shorebird release android --verbose
          
          # 4. Konversi AAB ke APK Universal
          # Langkah ini wajib agar Firebase menerima aplikasi tanpa link Play Store
          echo "🔄 Mengubah AAB menjadi APK..."
          java -jar bundletool.jar build-apks \
            --bundle=build/app/outputs/bundle/release/app-release.aab \
            --output=app.apks \
            --mode=universal \
          
          # 5. Ekstrak file APK dari archive .apks
          unzip -p app.apks universal.apk > app-release.apk

    # scripts:
    #   - name: Install Shorebird & Build Release
    #     script: |
    #       set -e
          
    #       # 1. Install Shorebird (Raw Source)
    #       echo "📥 Sedang menginstall Shorebird..."
    #       curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          
    #       # 2. Tambahkan Shorebird ke PATH
    #       export PATH="$HOME/.shorebird/bin:$PATH"
          
    #       # 3. Verifikasi Instalasi
    #       shorebird --version
          
    #       # 4. Setup Flutter Dependencies
    #       echo "📦 Mengambil dependencies..."
    #       flutter pub get
          
    #       # 5. Jalankan Shorebird Release (TANPA flag --flutter-version)
    #       # Shorebird akan otomatis menggunakan Flutter yang ada di Codemagic
    #       echo "🚀 Memulai Shorebird Release..."
    #       shorebird release android --verbose

    artifacts:
      - app-release.apk
          
    # artifacts:
    #   - build/app/outputs/bundle/release/app-release.apk
      
    publishing:
      firebase:
        # Menggunakan token dari grup "firebase"
        firebase_token: $FIREBASE_TOKEN 
        android:
          # Menggunakan App ID dari grup "firebase"
          app_id: $FIREBASE_APP_ID 
          # Pastikan kamu sudah membuat grup tester bernama "testers" di Firebase Console
          # Atau ganti dengan nama grup yang sesuai, misal: "android-team"
          groups:
            - internal-testers